### ISSUE TITLE
Partial refunds show wrong line total

### ISSUE THREAD

**Issue by pamil** [Sylius/RefundPlugin#83] opened 2018-10-02 09:04 UTC
I had a line item with shipping method "UPS" which was $95. I have refunded $53 and it shows correctly for the refund total, but not for the line total. The same happens in the PDF.

<img width="1408" alt="screenshot 2018-10-02 at 10 51 40" src="https://user-images.githubusercontent.com/1897953/46338883-a6dd0580-c631-11e8-8112-0617b850b762.png">

**Comment by Zales0123** [comment] 2018-10-02 09:05
Duplicate of https://github.com/Sylius/RefundPlugin/issues/65

**Closed by Zales0123** 2018-10-02 09:05 UTC
Labels: Hacktoberfest, bug
