### ISSUE TITLE
Bug with tax and shipments

### ISSUE THREAD

**Issue by prigal** [Sylius/RefundPlugin#110] opened 2019-01-29 13:19 UTC
When calculating refunds on shipments, there are 3 bugs : 

1. Only first shipment is refunded (it fails if you have multiple shipments)
2. Tax is not applied actually
3. Order shipping promotion adjustment is not refunded

**About which tax to apply.**
For each unit you already rebuild tax from order item unit data (and not from variant/product/zone matching). That works but for shipments that's not working as long tax of each shipment is not stored per shipment adjustment but on a single order shipping adjustment, you should sum all shipment adjustement and calculate tax ratio with tax adjustment linked to the order to find which tax has been applied to a shipment.

_(That will fail in case of multiple shipments with different tax on each shipments but I'm not sure it's really a use case in the context of a single order.)_

**Comment by jcgdjob** [comment] 2019-01-30 02:47
Does Sylius support multiple shipments?

**Comment by Zales0123** [comment] 2019-01-30 08:03
Hello Pierre and thank you for the issue. The problem is, plugin focuses on providing refund functionality for Sylius core. And indeed, Sylius **allows** multiple shipments per one order, but does not really **support** it - which means we usually assume there is one (or none) shipment on each order. In general, it does not provide any errors (order/checkout handling is quite straight-forward) but I can imagine it can be buggy in case of such a fragile feature as refunds.

I leave it as a bug, it would be great if we can fix these issues without influencing current plugin logic too much. It will probably not be fixed by us in the **nearest nearest** future, but maybe during the stabilization phase after the release of Sylius 1.4 (hopefully 😄), we will be able to do something in this case.

Of course, if you have some idea how to solve one or more of listed issues, feel welcomed to do that 🖖

**Comment by prigal** [comment] 2019-01-30 10:05
Hello Mateusz, we have fixed them in our fork, but we have no time actually to PR them properly as long as we did some specific work in the fork (like fees on a refund). 
 
Feel free to pick them up here https://github.com/printoclock/RefundPlugin.

About multi shipment, we dit not solve the problem completly as long as it will require some bigger modification to handle each shipment separately, but at least, it's no more wrong in calculation and taxes.

**Comment by prigal** [comment] 2019-01-30 10:21
@Zales0123, short list of what we do in our fork : 
- multi shipping with tax and promotion fixes
- refund grid
- adding editable fees on refund (cancelling an order and refunding money properly can be long depending on payment gateway, so we can take a fee for the task)
- handling refund states on sylius_order.payment_state instead of on sylius_order.state #111 
- minor bug fixes.

**Comment by GSadee** [comment] 2021-01-21 07:43
This issue is only partially fixed

**Closed** 2021-03-24 14:00 UTC
Labels: Bug
