### ISSUE TITLE
[Bug] Can't refund adjustment

### ISSUE THREAD

**Issue by vasilvestre** [Sylius/RefundPlugin#400] opened 2023-02-09 08:50 UTC
**SyliusRefundPlugin version affected**: 1.3.0

**Description**  
Can't refund adjustments, I use them as platform fees and they are not displayed in the plugin.

**Steps to reproduce**  
Create an extra adjustment that increases the total of the cart. I've tried to add the adjustment to the order and/or item, but none works.

```php
$adjustment = new Adjustment();
$adjustment->setType(AdjustmentInterface::ORDER_PROMOTION_ADJUSTMENT);
$adjustment->setAmount((int) round($order->getItemsTotal() * 8 / 100)); // 8% of items

$order->addAdjustment($adjustment);
// or
$order->getItems()->first()->addAdjustment($adjustment);
```

**Possible Solution**  
Add adjustment in the listed refund screen. In screen 1 you can see the 8€ as platform fees. Then in the refund screen (2) it doesn't show... I get that most adjustment decrease the total but not here.

![image](https://user-images.githubusercontent.com/17164385/217762373-eb476878-4a8d-41ff-9246-dbe63e4f0b5c.png)
![image](https://user-images.githubusercontent.com/17164385/217762645-cb02a67b-47f9-488e-8354-14e24bb846b1.png)

**Comment by GSadee** [comment] 2023-02-16 13:55
Hey @vasilvestre! 
If I understand correctly, you are customising the order to add your own adjustment there, so inevitably you will also need to customise the RefundPlugin to take into account the adjustment you have added, as by default we only allow the return of items and adjustments of the shipping type. In my opinion, this is not a bug and I also don't really know what you would expect as an improvement. 
Therefore I am closing this issue, but of course, I encourage you to open a new one if something actually turns out to be a bug in this plugin, or there will be a need for changes in our code to ease potential customisations using your example 🖖🏻

**Closed as completed by GSadee** 2023-02-16 13:55 UTC
Labels: Help Wanted

**Comment by vasilvestre** [comment] 2023-02-16 15:00
> Hey @vasilvestre! 
> If I understand correctly, you are customising the order to add your own adjustment there, so inevitably you will also need to customise the RefundPlugin to take into account the adjustment you have added, as by default we only allow the return of items and adjustments of the shipping type. In my opinion, this is not a bug and I also don't really know what you would expect as an improvement. 
> Therefore I am closing this issue, but of course, I encourage you to open a new one if something actually turns out to be a bug in this plugin, or there will be a need for changes in our code to ease potential customisations using your example 🖖🏻 

Sorry I should have updated the issue ! The adjustment shows if they are at Unit level :) and the refund just works. Thank you for input
