### ISSUE TITLE
[Bug] unable to open file 

### ISSUE THREAD

**Issue by mickael-naturopera** [Sylius/RefundPlugin#398] opened 2023-02-03 11:48 UTC
**SyliusRefundPlugin version affected**: 1.0

[Application] Feb  3 11:35:33 |CRITICA| PHP    Uncaught Exception: Unable to open file for reading [C:\Users\MICKAE~1\AppData\Local\Temp/2023_02_000008005.pdf]
[Application] Feb  3 11:35:33 |CRITICA| REQUES Uncaught PHP Exception Swift_IoException: "Unable to open file for reading [C:\Users\MICKAE~1\AppData\Local\Temp/2023_02_000008005.pdf]" at C:\naturopera_old\tidoo_backup\vendor\swiftmailer\swiftmailer\lib\classes\Swift\ByteStream\FileByteStream.php line 131
[Web Server ] [03-Feb-2023 11:35:34 UTC] PHP Fatal error:  Uncaught Swift_IoException: Unable to open file for reading [C:\Users\MICKAE~1\AppData\Local\Temp/2023_02_000008005.pdf] in C:\naturopera_old\tidoo_backup\vendor\swiftmailer\swiftmailer\lib\classes\Swift\ByteStream\FileByteStream.php:131
[Web Server ] Stack trace:
[Web Server ] #0 C:\naturopera_old\tidoo_backup\vendor\swiftmailer\swiftmailer\lib\classes\Swift\ByteStream\FileByteStream.php(77): Swift_ByteStream_FileByteStream->getReadHandle()
[Web Server ] #1 C:\naturopera_old\tidoo_backup\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Mime\ContentEncoder\Base64ContentEncoder.php(40): Swift_ByteStream_FileByteStream->read(8192)
[Web Server ] #2 C:\naturopera_old\tidoo_backup\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Mime\SimpleMimeEntity.php(555): Swift_Mime_ContentEncoder_Base64ContentEncoder->encodeByteStream(Object(Swift_ByteStream_FileByteStream), Object(Swift_Transport_StreamBuffer), 0, 76)
[Web Server ] #3 C:\naturopera_old\tidoo_backup\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Mime\SimpleMimeEntity.php(532): Swift_Mime_SimpleMimeEntity->bodyToByteStream(Ob in C:\naturopera_old\tidoo_backup\vendor\symfony\symfony\src\Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage.php on line 152
[Application] Feb  3 11:35:34 |CRITICA| REQUES Exception thrown when handling an exception (RuntimeException: Failed to start the session because headers have already been sent by "C:\naturopera_old\tidoo_backup\vendor\symfony\symfony\src\Symfony\Component\HttpFoundation\Response.php" at line 1224. at C:\naturopera_old\tidoo_backup\vendor\symfony\symfony\src\Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage.php line 152)
[Application] Feb  3 11:35:34 |CRITICA| PHP    Uncaught Exception: Failed to start the session because headers have already been sent by "C:\naturopera_old\tidoo_backup\vendor\symfony\symfony\src\Symfony\Component\HttpFoundation\Response.php" at line 1224.
[Application] Feb  3 11:35:34 |INFO   | PHP    User Deprecated: The "Symfony\Component\Debug\Exception\FatalThrowableError" class is deprecated since Symfony 4.4.
[Application] Feb  3 11:35:34 |INFO   | PHP    User Deprecated: The "Symfony\Component\Debug\Exception\FatalErrorException" class is deprecated since Symfony 4.4, use "Symfony\Component\ErrorHandler\Error\FatalError" instead.
[Application] Feb  3 11:35:34 |CRITICA| PHP    Error: Uncaught Swift_IoException: Unable to open file for reading [C:\Users\MICKAE~1\AppData\Local\Temp/2023_02_000008005.pdf] in C:\naturopera_old\tidoo_backup\vendor\swiftmailer\swiftmailer\lib\classes\Swift\ByteStream\FileByteStream.php:131 Stack trace: #0 C:\naturopera_old\tidoo_backup\vendor\swiftmailer\swiftmailer\lib\classes\Swift\ByteStream\FileByteStream.php(77): Swift_ByteStream_FileByteStream->getReadHandle() #1 C:\naturopera_old\tidoo_backup\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Mime\ContentEncoder\Base64ContentEncoder.php(40): Swift_ByteStream_FileByteStream->read(8192) #2 C:\naturopera_old\tidoo_backup\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Mime\SimpleMimeEntity.php(555): Swift_Mime_ContentEncoder_Base64ContentEncoder->encodeByteStream(Object(Swift_ByteStream_FileByteStream), Object(Swift_Transport_StreamBuffer), 0, 76) #3 C:\naturopera_old\tidoo_backup\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Mime\SimpleMimeEntity.php(532): Swift_Mime_SimpleMimeEntity->bodyToByteStream(Ob

I have no problem with invoicing but with refund this error 
i ty to check in CreditMemoEmailSender.php 
var_dump($this->fileManager->realPath($filePath)); die;

When dump and die file is created and copy the path i can open the file.
Else if no var_dump and die, all the time the Error Unable to open file for reading [C:\Users\MICKAE~1\AppData\Local\Temp/2023_02_000008005.pdf]

I get this error in local env and prod env

**Comment by GSadee** [comment] 2023-02-16 13:10
Hi, I am unable to reproduce this error on the latest version of plugin, this could already has been fixed. What is more, in the latest version, the only one, that is supported, we've introduced [saving credit memos during generation](https://github.com/Sylius/RefundPlugin/pull/373), which can probably resolve this problem of accessing to temporary PDFs. 

I'm closing this issue and I would like to encourage you to use [Slack](https://sylius-devs.slack.com/join/shared_invite/zt-1l2jgziyf-YavChVJasnUMS_xstCnJtg#/shared-invite/email) to resolve your issue or try to update the plugin to the latest version. 

Of course, if it turns out that the bug lies with our code, I encourage you to open an issue, or preferably a contribution with a fix 🖖🏻

**Closed as completed by GSadee** 2023-02-16 13:10 UTC
Labels: Bug
