### ISSUE TITLE
Disable default refund button ?

### ISSUE THREAD

**Issue by vasilvestre** [Sylius/RefundPlugin#399] opened 2023-02-08 08:24 UTC
In my admin, the refund button under payment do not uses this plugin and create a payment refund. Not a "sylius_refund_refund".. which is confusing.
This button should either be disabled or the behavior should be change AFAIK.

Am I using this plugin wrong ?

On this picture, the "remboursement" button under the main payment leads to a state machine.
![image](https://user-images.githubusercontent.com/17164385/217476509-4fd984a5-26ca-4375-9d05-cea76952a442.png)

 When the top button is clicked, it leads to this page :

![image](https://user-images.githubusercontent.com/17164385/217476762-ffd2ff28-bf92-4474-8b43-acd634adfed6.png)

**Comment by lchrusciel** [comment] 2023-02-08 10:14
You are totally correct. This button should be disabled/behaviour should change. Long term best solution would be to add Sylius ui event for it and remove it in configuration. Short term solution is to override the template to hide it. 

There could be an option to change the behaviour. Still, as this plugin is not refunding payments but rather orders, we would need to figure out proper behaviour (distribute given payment among items, perhaps).

**Comment by vasilvestre** [comment] 2023-02-08 10:19
> You are totally correct. This button should be disabled/behaviour should change. Long term best solution would be to add Sylius ui event for it and remove it in configuration. Short term solution is to override the template to hide it.
> 
> There could be an option to change the behaviour. Still, as this plugin is not refunding payments but rather orders, we would need to figure out proper behaviour (distribute given payment among items, perhaps).

Wonderful, I will do it. Thank you :)

**Comment by GSadee** [comment] 2023-02-16 13:53
Hi @vasilvestre!
I've tried to recreate the issue as it seemed strange to me that this button appeared, because it is disabled in the [configuration file](https://github.com/Sylius/RefundPlugin/blob/1.3/src/Resources/config/app/config.yml#L174:L177), but without success. This seems to work as intended 🤔 Are you sure you are loading this configuration file in your application and not overwriting either the specified template or the event configuration? 
Nevertheless, since it seems to be working, I am closing this issue, but feel free to comment or reopen it if something is indeed wrong with our implementation 🖖🏻

**Closed as completed by GSadee** 2023-02-16 13:53 UTC
Labels: Help Wanted

**Comment by vasilvestre** [comment] 2023-02-16 15:03
> Hi @vasilvestre!
> I've tried to recreate the issue as it seemed strange to me that this button appeared, because it is disabled in the [configuration file](https://github.com/Sylius/RefundPlugin/blob/1.3/src/Resources/config/app/config.yml#L174:L177), but without success. This seems to work as intended 🤔 Are you sure you are loading this configuration file in your application and not overwriting either the specified template or the event configuration? 
> Nevertheless, since it seems to be working, I am closing this issue, but feel free to comment or reopen it if something is indeed wrong with our implementation 🖖🏻 

It should be loaded by default ? Anything manual to do ?

**Comment by vasilvestre** [comment] 2023-02-16 15:04
> Hi @vasilvestre!
> I've tried to recreate the issue as it seemed strange to me that this button appeared, because it is disabled in the [configuration file](https://github.com/Sylius/RefundPlugin/blob/1.3/src/Resources/config/app/config.yml#L174:L177), but without success. This seems to work as intended 🤔 Are you sure you are loading this configuration file in your application and not overwriting either the specified template or the event configuration? 
> Nevertheless, since it seems to be working, I am closing this issue, but feel free to comment or reopen it if something is indeed wrong with our implementation 🖖🏻 

Oh.. the readme do not tell about this, I will tryagain

**Comment by GSadee** [comment] 2023-02-17 14:12
But it should work out of the box, without any additional configuration, apart from loading the main plugin configuration, which should be added by default by the Symfony Flex, or manually if you don't use it which is mentioned in the installation guide: https://github.com/Sylius/RefundPlugin/blob/1.4/docs/legacy_installation.md

Still, if there will be any problems, and it doesn't work as it should, feel free to raise the issue again 😃

**Comment by vasilvestre** [comment] 2023-03-17 10:16
So I'm not alone and I had to copy the original file `Order/Show/_payment.html.twig` to `templates/bundles/SyliusAdminBundle/Order/Show/_payment.html.twig` and then comment the following part :


```
    {% if sm_can(payment, 'refund', 'sylius_payment') %}
        <div class="ui segment">
            <form action="{{ path('sylius_admin_order_payment_refund', {'orderId': order.id, 'id': payment.id}) }}" method="post" novalidate>
                <input type="hidden" name="_csrf_token" value="{{ csrf_token(payment.id) }}" />
                <input type="hidden" name="_method" value="PUT">
                <button type="submit" class="ui icon labeled tiny yellow fluid loadable button"><i class="reply all icon"></i> {{ 'sylius.ui.refund'|trans }}</button>
            </form>
        </div>
    {% endif %}
```

**Comment by artyuum** [comment] 2023-03-17 10:27
@vasilvestre helped, thanks.
